apiVersion: v1
entries:
  EoloPlanner:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-09-01T20:06:56.882842625+02:00"
    description: A Helm chart for Kubernetes
    digest: 86ccbe78642f82429340b661258de854657803b0c7267d2b164de7a6126f1169
    name: EoloPlanner
    type: application
    urls:
    - https://raw.githubusercontent.com/manulorente/mastercloudapps-co-p04/EoloPlanner/charts/EoloPlanner-0.0.1.tgz
    version: 0.0.1
generated: "2023-09-01T20:06:56.882113139+02:00"
